### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by WazirDeveloper93** [aleherr19/TikTok-downloader#1]
Can you make an app tiktok video downloader for me

**Comment by aleherr19** [comment]
Hey, sorry for the long wait. I could try, but it would only be available for Android devices. Is that okay?

**Comment by WazirDeveloper93** [comment]
ok

**Comment by khalilhoti** [comment]
hello sir i am calling that method but there are some parameters so cannot call method can you explain little bit more
or make example app of tiktok downloader
thank you

**Comment by WazirDeveloper93** [comment]
https://play.google.com/store/apps/details?id=com.tiktok.video.videodownloader

**Comment by WazirDeveloper93** [comment]
sorrty for late bro how much time is required to complete this app

**Comment by aleherr19** [comment]
I've updated the java code. I'm not sure if i'll release an app as there are many available on the play store already.
