### ISSUE TITLE
Without Watermark

### ISSUE THREAD

**Issue by amirmuhsin** [aleherr19/TikTok-downloader#3]
Hey mate, thanks for the repo it is very helpful :)

And I have been wondering  about downloading the videos from tiktok without watermark. Any idea and suggestions ?

**Comment by aleherr19** [comment]
At the moment, I'm not exactly sure. The video being downloaded has the watermark literally rendered within the video. I've seen other online services download videos without the watermark though. Looks like I'll have to look harder.
